[database]
host = "localhost"
port = "5432"
user = "postgres"
password = "postgrespass"
name = "bank"
table = "mockdata"
test-users = 1000

[pool]
default-size = 20
max-size = 100
size-increment = 5

[db-mysql]
host = "localhost"
port = "3306"
user = "mysql"
password = "mysqlpass"
name = "bank"
table = "mockdata"


[db-postgres]
host = "localhost"
port = "5432"
user = "postgres"
password = "postgrespass"
name = "bank"
table = "mockdata"
test-users = 1000

