[package]
name = "crypto-math-fundamentals"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
colorize = "0.1.0"
config = "0.15.11"
num-bigint = "0.4.6"
serde = { version = "1.0.219", features = ["derive"] }
