[package]
name = "suugaku"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = "1.1.3"
anyhow = "1.0.97"
clap = "4.5.31"
colored = "3.0.0"
indicatif = "0.17.11"
once_cell = "1.20.3"
petgraph = "0.7.1"
regex = "1.11.1"
