[package]
name = "hash-functions"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
colored = "3.0.0"
config = "0.15.11"
md5 = "0.7.0"
plotters = "0.3.7"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
sha1 = "0.10.6"
sha2 = "0.10.9"
